name= "pastebin-worker"
compatibility_date = "2023-11-28"
account_id= "41669a597f0fe340f9b7a1d291156f9e"
main = "src/index.ts"
workers_dev = false

vars = { ENVIRONMENT = "production" }
route = { pattern = "paste.1win.eu.org", custom_domain = true }

kv_namespaces = [
  { binding = "PB", id = "4d3ee59234fc4371836b1b395e88325c" },
  { binding = "PBIMGS", id ="2f484a2e1f964c9688bf54888ad36817" }
]

[site]
bucket = "./static/dist"
